# Generated by Django 5.1.6 on 2025-03-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='privacy_settings',
        ),
    ]
